import requests
import time
import sys
import re

url = raw_input('[*] Target url: ')

default = re.search(r'([\w:/\._-]+\?[\w_-]+=)([\w_-]+)', url)

i = default.groups()[0] + '\''


header = {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 5.0; SunOS 5.10 sun4u; X11)',
          'user-agent': 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.2pre) Gecko/20100207 Ubuntu/9.04 (jaunty) Namoroka/3.6.2pre',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Avant Browser;',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0)',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 5.1)',
          'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6)',
          'user-agent': 'Microsoft Internet Explorer/4.0b1 (Windows 95)',
          'user-agent': 'Opera/8.00 (Windows NT 5.1; U; en)',
          'user-agent': 'amaya/9.51 libwww/5.4.0',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 5.0; AOL 4.0; Windows 95; c_athome)',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)',
          'user-agent': 'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Kubuntu)',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; ZoomSpider.net bot; .NET CLR 1.1.4322)',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; QihooBot 1.0 qihoobot@qihoo.net)',
          'user-agent': 'Mozilla/4.0 (compatible; MSIE 5.0; Windows ME) Opera 5.11 [en]'
         }


errorMessages = {'Cannot open database requested by the login. The login failed.',
                 'The service has encountered an error processing your request. Please try again. Error code.',
                 'You receive this error when the service is down due to software or hardware upgrades, hardware failures, or any other failover problems. The error code embedded within the message of error 40197 provides additional information about the kind of failure or failover that occurred. Some examples of the error codes are embedded within the message of error 40197 are 40020, 40143, 40166, and 40540.',
                 'Reconnecting to your SQL Database server automatically connects you to a healthy copy of your database. Your application must catch error 40197, log the embedded error code within the message for troubleshooting, and try reconnecting to SQL Database until the resources are available, and your connection is established again.',
                 'The service is currently busy. Retry the request after 10 seconds. Incident ID:'
                 'Database on server is not currently available. Please retry the connection later. If the problem persists, contact customer support, and provide them the session tracing ID of ',
                 'Cannot process request. Not enough resources to process request.',
                 'The service is currently busy. Please retry the request later.',
                 'Cannot process create or update request. Too many create or update operations in progress for subscription',
                 'The service is busy processing multiple create or update requests for your subscription or server. Requests are currently blocked for resource optimization. Query sys.dm_operation_status for pending operations. Wait until pending create or update requests are complete or delete one of your pending requests and retry your request later.',
                 'Cannot process request. Too many operations in progress for subscription',
                 'The service is busy processing multiple requests for this subscription. Requests are currently blocked for resource optimization. Query sys.dm_operation_status for operation status. Wait until pending requests are complete or delete one of your pending requests and retry your request later.',
                 'Login to read-secondary failed due to long wait on "HADR_DATABASE_WAIT_FOR_TRANSITION_TO_VERSIONING". The replica is not available for login because row versions are missing for transactions that were in-flight when the replica was recycled. The issue can be resolved by rolling back or committing the active transactions on the primary replica. Occurrences of this condition can be minimized by avoiding long write transactions on the primary.',
                 'mysql_fetch_array()'
                }


try:
  req = requests.get(i, headers=header)
  html = req.text
  
except Exception as e:
  print '[!] Error: ' + e

except KeyboardInterrupt:
  print '[!] Exiting...'
  time.sleep(1.5)
  sys.quit()

vuln = 0
  
for message in errorMessages:
  if message in html:
    print '[!] Checking...'
    time.sleep(1.5)
    print '[+] Vulnerability found: ' + message
    vuln += 1

if vuln == 0:
  print '[-] Vulnerability not found'
  print '[!] Exiting...'
  time.sleep(1.5)
  sys.quit()

